services:
  backend:
    build:
      context: ../../backend
      dockerfile: Dockerfile

    depends_on:
      - postgres

    environment:
      DATABASE_URL: postgresql+psycopg://schedular:schedular@postgres:5432/schedular
      ENVIRONMENT: development

    ports:
      - "8000:8000"

    volumes:
      - ../../backend:/app

  postgres:
    image: postgres:16

    environment:
      POSTGRES_DB: schedular
      POSTGRES_USER: schedular
      POSTGRES_PASSWORD: schedular

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: