"""add confirmed proposal id

Revision ID: 300c4ef3c65e
Revises: ec8426316aae
Create Date: 2026-09-13 00:51:34.393148

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '300c4ef3c65e'
down_revision: str | Sequence[str] | None = 'ec8426316aae'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('confirmed_proposal_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'confirmed_proposal_id')
    # ### end Alembic commands ###
