"""add calendar source metadata

Revision ID: 7f60c1c680f9
Revises: 300c4ef3c65e
Create Date: 2026-09-14 00:10:24.340484

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7f60c1c680f9'
down_revision: str | Sequence[str] | None = '300c4ef3c65e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_sources', sa.Column('label', sa.String(length=64), nullable=True))
    op.add_column('calendar_sources', sa.Column('event_count', sa.Integer(), nullable=False))
    op.add_column('calendar_sources', sa.Column('created_at', sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_sources', 'created_at')
    op.drop_column('calendar_sources', 'event_count')
    op.drop_column('calendar_sources', 'label')
    # ### end Alembic commands ###
