"""add user notification preference

Revision ID: bcb51f836df7
Revises: 02daa394a268
Create Date: 2026-09-13 00:54:05.237571

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bcb51f836df7"
down_revision: str | Sequence[str] | None = "02daa394a268"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("notify_email_default", sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "notify_email_default")
    # ### end Alembic commands ###
