"""add availability submission tracking

Revision ID: ec8426316aae
Revises: bcb51f836df7
Create Date: 2026-09-13 01:33:52.381584

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ec8426316aae"
down_revision: str | Sequence[str] | None = "bcb51f836df7"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "memberships",
        sa.Column(
            "availability_submitted_at", sa.DateTime(timezone=True), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("memberships", "availability_submitted_at")
    # ### end Alembic commands ###
