"""add availability submission tracking

Revision ID: ec8426316aae
Revises: bcb51f836df7
Create Date: 2026-09-13 01:33:52.381584

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ec8426316aae'
down_revision: Union[str, Sequence[str], None] = 'bcb51f836df7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memberships', sa.Column('availability_submitted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memberships', 'availability_submitted_at')
    # ### end Alembic commands ###
